package rules;
global java.util.List list
dialect "mvel"

rule "Prefiltrado: Autos de menos de 200000 pesos"
		salience(1000)
	when
		c: Car (precio > 200000)
	then
		retract(c);
end

rule "(1) Regla 1: Precio"
		salience(999)
    when
        Attribute (name == "Precio", v: value > 0)
        c: Car (precio > (46000+14000*v) || precio == 0)
    then
        retract(c);
end

rule "(2) Regla 2: Sexo - masculino"
		salience(500)
    when
        Attribute (name == "Sexo", value == 1)
        at1: Attribute (name == "Potencia")
    then
        at1.value = at1.value + 1;
end

rule "(2) Regla 3: Sexo - femenino"
		salience(500)
    when
        Attribute (name == "Sexo", value == 2)
        at1: Attribute (name == "Diseño")
        at2: Attribute (name == "Potencia")
        at3: Attribute (name == "Confort")
    then
        at1.value = at1.value + 1;
        at2.value = at2.value - 2;
        at3.value = at3.value + 1; 
end

rule "(3) Regla 4: Uso - Ir a trabajar o trabajar con el vehículo"
		salience(500)
    when
        Attribute (name == "Uso" && (value == 1 || value == 4))
        at1: Attribute (name == "Diseño")

    then
        at1.value = at1.value - 2;
end

rule "(3) Regla 5: Uso - Fines de semana"
		salience(500)
    when
        Attribute (name == "Uso", value == 2)
        at1: Attribute (name == "Diseño")
		at2: Attribute (name == "Entretenimiento")
		at3: Attribute (name == "Ruta")
    then
        at1.value = at1.value + 1;
        at2.value = at2.value + 1;
        at3.value = 1;
end

rule "(3) Regla 6: Uso - Vacaciones largas distancias 1"
		salience(500)
    when
        Attribute (name == "Uso", value == 3)
        at1: Attribute (name == "Confort")
		at2: Attribute (name == "Entretenimiento")
		at3: Attribute (name == "Ruta")
    then
        at1.value = at1.value + 1;
        at2.value = at2.value + 1;
        at3.value = 1;
end

rule "(3) Regla 7: Uso - Vacaciones largas distancias 2"
		salience(500)
    when
        Attribute (name == "Uso", value == 3)
		c: Car (tanque < 3)
    then
        retract (c);
end

rule "(4) Regla 8: Menores - Sí"
		salience(500)
    when
        Attribute (name == "Menores", value == 1)
        at1: Attribute (name == "Seguridad")
		at2: Attribute (name == "MenoresSN")
    then
        at1.value = at1.value + 2;
        at2.value = 1;
end

rule "(4) Regla 9: Menores - No"
		salience(500)
    when
        Attribute (name == "Menores", value == 2)
		at1: Attribute (name == "MenoresSN")
    then
        at1.value = 0;
end

rule "(5) Regla 10: Edad - 18 a 25"
		salience(500)
    when
        Attribute (name == "Edad", value == 1)
		at1: Attribute (name == "Potencia")
		at2: Attribute (name == "Entretenimiento")
    then
        at1.value = at1.value + 3;
        at2.value = at2.value + 2;
end

rule "(5) Regla 11: Edad - 26 a 45"
		salience(500)
    when
        Attribute (name == "Edad", value == 2)
		at1: Attribute (name == "Potencia")
		at2: Attribute (name == "Diseño")
		at3: Attribute (name == "Seguridad")
    then
        at1.value = at1.value + 2;
        at2.value = at2.value + 2;
        at3.value = at3.value + 1;
end

rule "(5) Regla 12: Edad - 46 a 60"
		salience(500)
    when
        Attribute (name == "Edad", value == 3)
		at1: Attribute (name == "Diseño")
		at2: Attribute (name == "Seguridad")
		at3: Attribute (name == "Confort")
    then
        at1.value = at1.value + 3;
        at2.value = at2.value + 2;
        at3.value = at3.value + 2;
end

rule "(5) Regla 13: Edad - Más de 60"
		salience(500)
    when
        Attribute (name == "Edad", value == 4)
		at1: Attribute (name == "Seguridad")
		at2: Attribute (name == "Confort")
		at3: Attribute (name == "Entretenimiento")
    then
        at1.value = at1.value + 2;
        at2.value = at2.value + 3;
        at3.value = at3.value - 1;
end

rule "(6) Regla 14: Distancia a lugar de trabajo - 0 a 10 km"
		salience(500)
    when
        Attribute (name == "DistanciaTrabajo", value == 1)
		at1: Attribute (name == "DistanciaMes")
    then
        at1.value = 220;
end

rule "(6) Regla 15: Distancia a lugar de trabajo - 10 a 30 km"
		salience(500)
    when
        Attribute (name == "DistanciaTrabajo", value == 2)
		at1: Attribute (name == "DistanciaMes")
    then
        at1.value = 880;
end

rule "(6) Regla 16: Distancia a lugar de trabajo - 30 a 100 km"
		salience(500)
    when
        Attribute (name == "DistanciaTrabajo", value == 3)
		at1: Attribute (name == "DistanciaMes")
    then
        at1.value = 2680;
end

rule "(6) Regla 17: Distancia a lugar de trabajo - Más de 100 km"
		salience(500)
    when
        Attribute (name == "DistanciaTrabajo", value == 4)
		at1: Attribute (name == "DistanciaMes")
    then
        at1.value = 8800;
end

rule "(7) Regla 18: Viaje al trabajo por ruta o autopista - Sí"
		salience(500)
    when
        Attribute (name == "RutaTrabajo", value == 1)
		at1: Attribute (name == "Ruta")
    then
        at1.value = 1;
end

rule "(7) Regla 19: Viaje al trabajo por ruto o autopista - No"
		salience(500)
    when
        Attribute (name == "RutaTrabajo", value == 2)
		at1: Attribute (name == "Ruta")
    then
        at1.value = 0;
end

rule "(8) Regla 20: Distancia fines de semana - 0 a 50 km o NS/NC"
		salience(500)
    when
        Attribute (name == "DistanciaFinesDeSemana", (value == 1||value == 0))
		at1: Attribute (name == "DistanciaMes")
    then
        at1.value = 216;
end

rule "(8) Regla 21: Distancia fines de semana - 50 a 200 km"
		salience(500)
    when
        Attribute (name == "DistanciaFinesDeSemana", value == 2)
		at1: Attribute (name == "DistanciaMes")
    then
        at1.value = 1082;
end

rule "(8) Regla 22: Distancia fines de semana - Más de 200 km"
		salience(500)
    when
        Attribute (name == "DistanciaFinesDeSemana", value == 3)
		at1: Attribute (name == "DistanciaMes")
    then
        at1.value = 2598;
end

rule "(9) Regla 23: Cantidad de viajes al año - Uno"
		salience(500)
    when
        Attribute (name == "CantVacaciones", value == 1)
		at1: Attribute (name == "CantViajes")
    then
        at1.value = 1;
end

rule "(9) Regla 24: Cantidad de viajes al año - Dos"
		salience(500)
    when
        Attribute (name == "CantVacaciones", value == 2)
		at1: Attribute (name == "CantViajes")
    then
        at1.value = 2;
end

rule "(10) Regla 25: Viaja diariamente por su trabajo - Sí"
		salience(500)
    when
        Attribute (name == "DiarioTrabajo", value == 1)
		at1: Attribute (name == "DistanciaMes")
    then
        at1.value = 1500;
end

rule "(10) Regla 26: Viaja diariamente por su trabajo - No"
		salience(500)
    when
        Attribute (name == "DiarioTrabajo", value == 2)
		at1: Attribute (name == "DistanciaMes")
    then
        at1.value = 1200;
end

rule "(11) Regla 27: Transporta por trabajo - Personas"
		salience(500)
    when
        Attribute (name == "TransporteTrabajo", value == 1)
		c: Car (largo <= 4500)
    then
        retract (c);
end

rule "(11) Regla 28: Transporta por trabajo - Carga 1"
		salience(500)
    when
        Attribute (name == "TransporteTrabajo", value == 2)
		at1: Attribute (name == "Carga")
    then
        at1.value = 1;
end

rule "(11) Regla 29: Transporta por trabajo - Carga 2"
		salience(500)
    when
        Attribute (name == "TransporteTrabajo", value == 2)
		c: Car (ancho <= 1850 || largo <= 4600 || alto <= 1700 || capacidadCarga <= 600)
    then
        retract (c);
end

rule "(12) Regla 30: Uso para trabajo ruta o autopista - Sí"
		salience(500)
    when
        Attribute (name == "RutaOAutopistaTrabajo", value == 1)
		at1: Attribute (name == "Seguridad")
		at2: Attribute (name == "Ruta")
    then
        at1.value = at1.value + 1;
		at2.value = 1;
end

rule "(12) Regla  31: Uso para trabajo ruta o autopista - No"
		salience(500)
    when
        Attribute (name == "RutaOAutopistaTrabajo", value == 2)
		at1: Attribute (name == "Ruta")
    then
        at1.value = 0;
end

rule "(13) Regla 32: Transporte de menores - 1 a 3 1"
		salience(500)
    when
        Attribute (name == "CantMenores", value == 1)
		at1: Attribute (name == "Entretenimiento")
    then
        at1.value = at1.value + 1;
end

rule "(13) Regla 33: Transporte de menores - 1 a 3 2"
		salience(500)
    when
        Attribute (name == "CantMenores", value == 1)
		c: Car (largo <= 4250)
    then
        retract (c);
end

rule "(13) Regla 34: Transporte de menores - Más de 4 1"
		salience(500)
    when
        Attribute (name == "CantMenores", value == 2)
		at1: Attribute (name == "Entretenimiento")
    then
        at1.value = at1.value + 1;
end

rule "(13) Regla 35: Transporte de menores - Más de 4 2"
		salience(500)
    when
        Attribute (name == "CantMenores", value == 2)
		c: Car (largo <= 4250)
    then
        retract (c);
end

rule "(14) Regla 36: Experiencia de manejo - 0 a 2 años"
		salience(500)
    when
        Attribute (name == "Experiencia", value == 1)
        at1: Attribute (name == "Seguridad")
        at2: Attribute (name == "CajaAutomatica")
    then
        at1.value = at1.value + 1;
        at2.value = 1;
end

rule "(15) Regla 37: Combustible - Nafta"
		salience(500)
    when
        Attribute (name == "Combustible", value == 1)
		c: Car (combustible == "Diesel")
    then
        retract (c);
end

rule "(15) Regla 38: Combustible - Diesel"
		salience(500)
    when
        Attribute (name == "Combustible", value == 2)
		c: Car (combustible != "Diesel")
    then
        retract (c);
end

rule "(16) Regla 39: Música - MP3"
		salience(500)
    when
        Attribute (name == "Musica", value == 3)
        at1: Attribute (name == "MP3")
    then
        at1.value = 1;
end

rule "(17) Regla 40: Tecnología - Muy buena"
		salience(500)
    when
        Attribute (name == "Tecnologia", value == 1)
        at1: Attribute (name == "Tecnologia2")
    then
        at1.value = 1.25;
end

rule "(17) Regla  41: Tecnología - Buena"
		salience(500)
    when
        Attribute (name == "Tecnologia", value == 2)
        at1: Attribute (name == "Tecnologia2")
    then
        at1.value = 1;
end

rule "(17) Regla 42: Tecnología - Regular"
		salience(500)
    when
        Attribute (name == "Tecnologia", value == 3)
        at1: Attribute (name == "Tecnologia2")
    then
        at1.value = 0.75;
end

rule "(17) Regla 43: Tecnología - Mala"
		salience(500)
    when
        Attribute (name == "Tecnologia", value == 4)
        at1: Attribute (name == "Tecnologia2")
    then
        at1.value = 0.5;
end

rule "(18) Regla 44: Importante - Potencia del motor"
		salience(500)
    when
        Attribute (name == "Importante", value == 1)
        at1: Attribute (name == "Potencia")
    then
        at1.value = at1.value * 1.2;
end

rule "(18) Regla 45: Importante - Aspecto"
		salience(500)
    when
        Attribute (name == "Importante", value == 2)
        at1: Attribute (name == "Diseño")
    then
        at1.value = at1.value * 1.3;
end

rule "(18) Regla 46: Importante - Confort"
		salience(500)
    when
        Attribute (name == "Importante", value == 3)
        at1: Attribute (name == "Confort")
    then
        at1.value = at1.value * 1.2;
end

rule "(18) Regla 47: Importante - Entretenimiento"
		salience(500)
    when
        Attribute (name == "Importante", value == 4)
        at1: Attribute (name == "Entretenimiento")
    then
        at1.value = at1.value * 1.2;
end

rule "(18) Regla 48: Importante - Seguridad"
		salience(500)
    when
        Attribute (name == "Importante", value == 5)
        at1: Attribute (name == "Seguridad")
    then
        at1.value = at1.value * 1.1;
end

rule "(19) Regla 49: Gastos"
		salience(400)
    when
        Attribute (name == "Gasto", v: value > 0)
        Attribute (name == "DistanciaMes",vd: value)
        Attribute (name == "Ruta",vr: value)
        c: Car ((precio*0.00627+(vd/100)*(consumoEnRuta*vr+consumoEnCiudad*(1-vr)) ) > (400+400*v))
    then
        retract(c);
end

rule "(20) Regla 50: Kilómetros por viaje"
		salience(450)
    when
        Attribute (name == "KmViaje1", v: value > 0)
        Attribute (name == "CantViajes", vc: value)
        at1: Attribute (name == "DistanciaMes")
    then
        at1.value = vc*v*100;
end

rule "(20) Regla 51: Kilómetros por viaje"
		salience(450)
    when
        Attribute (name == "KmViaje2", v: value > 0)
        Attribute (name == "CantViajes", vc: value)
        at1: Attribute (name == "DistanciaMes")
    then
        at1.value = vc*v*100;
end

rule "(21) Regla 52: Kilómetros por viaje"
		salience(450)
    when
        Attribute (name == "KmViaje3", v: value > 0)
        at1: Attribute (name == "DistanciaMes")
    then
        at1.value = v*1000/12;
end

rule "(22) Regla 53: Pasajeros transportados - 6 a 8"
		salience(500)
    when
        Attribute (name == "CantPasajeros", value == 3)
		c: Car (capacidadCarga <= 1500)
    then
        retract (c);
end

rule "(22) Regla 54: Pasajeros transportados - Más de 8"
		salience(500)
    when
        Attribute (name == "CantPasajeros", value == 4)
		c: Car (capacidadCarga <= 1500)
    then
        retract (c);
end

rule "(23) Regla 55: Carga transportada"
		salience(500)
    when
        Attribute (name == "CantPasajeros", v: value > 0)
		c: Car (capacidadCarga <= (v*500))
    then
        retract (c);
end

rule "(24) Regla 56: Mayor frecuencia de noche - Sí"
		salience(500)
    when
        Attribute (name == "Noche", value == 1)
		c: Car (airbagConductor == 0)
    then
        retract (c);
end

rule "(25) Regla 57: Transmisión - Manual"
		salience(500)
    when
        Attribute (name == "Transmision", value == 1)
		c: Car (transmision != 1)
    then
        retract (c);
end

rule "(25) Regla 57: Transmisión - Automática"
		salience(500)
    when
        Attribute (name == "Transmision", value == 2)
		c: Car (transmision == 1)
    then
        retract (c);
end

rule "(26) Regla 58: Auto híbrido - No"
		salience(500)
    when
        Attribute (name == "Hibrido1", value == 2)
		c: Car (combustible != "Hibrido")
    then
        retract (c);
end

rule "(26) Regla 59: Auto híbrido - No"
		salience(500)
    when
        Attribute (name == "Hibrido2", value == 2)
		c: Car (combustible != "Hibrido")
    then
        retract (c);
end

rule "Potencia"
		salience(100)
	when
		c: Car ()
		Attribute (name == "Carga",v: value)
	then
		c.potenciaDrl = (3/525) * c.potencia + (2/760)*v* c.torque + (2/316) * (1-v) *c.velocidad;
end

rule "Seguridad"
		salience(100)
	when
		c: Car ()
		Attribute (name == "Ruta", v: value)
		Attribute (name == "MenoresSN", vm: value)
	then
		c.seguridadDrl = 1.7 + 0.8 * (1 - (0.5*v + 0.5*vm)) + (0.8 + (0.2*v + 0.2*vm))*c.abs + (0.9 + 0.4*v)*(c.airbagConductor/3) + 0.3*vm*c.cinturones;	
end

rule "Confort"
		salience(100)
	when
		c: Car ()
		Attribute (name == "CajaAutomatica",v: value)
	then
		c.confortDrl = (0.5+v)*(c.transmision-1)+(1.2/4)*c.aireAcondicionado+0.8*c.cierrePuertas+(2.5-v)*(0.05*c.direccion+0.05*c.espejosExternos+0.05*c.vidrios+0.05*c.velocidadCrucero+0.05+0.05*c.computadoraABordo+0.05*c.sensorLluvia+0.05*c.balizaAut+0.05*c.camaraTrasera);
end

rule "Entretenimiento"
		salience(100)
	when
		c: Car ()
		Attribute (name == "Tecnologia2",v: value)
		Attribute (name == "MP3",vm: value)
	then
		c.entretenimientoDrl = (v + 1/4)*(1.5*(0.95*c.equipoMusica+0.05*vm)+c.parlantes+0.5*c.bluetooth+0.5*c.gps+0.2*c.conexionAuxiliar+0.4*c.conexionUsb+0.4*c.controlPorVoz);
end



rule "Selección"
	when
		c: Car ()
	then
		c.selected = 1;
end
